#include <iostream>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>
#include <algorithm>
#include <filesystem>

namespace fs = std::filesystem;

std::string toConstName(const std::string& filename) {
    std::string name = filename;
    size_t dot = name.rfind('.');
    if (dot != std::string::npos) name = name.substr(0, dot);
    std::transform(name.begin(), name.end(), name.begin(), ::toupper);
    return name;
}

int main() {
    const std::string TEMPLATES_DIR = "web/templates";
    const std::string OUTPUT_FILE   = "web/templates_generated.hpp";

    std::vector<fs::path> htmlFiles;
    for (const auto& entry : fs::directory_iterator(TEMPLATES_DIR)) {
        if (entry.path().extension() == ".html") {
            htmlFiles.push_back(entry.path());
        }
    }
    std::sort(htmlFiles.begin(), htmlFiles.end());

    if (htmlFiles.empty()) {
        std::cerr << "Error: no .html files found in " << TEMPLATES_DIR << "\n";
        return 1;
    }

    std::ofstream out(OUTPUT_FILE);
    if (!out.is_open()) {
        std::cerr << "Error: cannot write to " << OUTPUT_FILE << "\n";
        return 1;
    }

    out << "// AUTO-GENERATED FILE — DO NOT EDIT\n";
    out << "// Generated by embed_templates from web/templates/\n";
    out << "#pragma once\n";
    out << "#include <string>\n\n";
    out << "namespace Templates {\n\n";

    for (const auto& path : htmlFiles) {
        std::ifstream f(path);
        if (!f.is_open()) {
            std::cerr << "Warning: cannot read " << path << "\n";
            continue;
        }

        std::stringstream buf;
        buf << f.rdbuf();
        std::string content = buf.str();

        std::string constName = toConstName(path.filename().string());

        out << "inline const std::string " << constName << " = R\"HTMLEND(\n";
        out << content;
        out << ")HTMLEND\";\n\n";

        std::cout << "  embedded: " << constName << " (" << content.size() << " bytes)\n";
    }

    out << "} // namespace Templates\n";
    out.close();

    std::cout << "Generated " << OUTPUT_FILE << " with " << htmlFiles.size() << " templates\n";
    return 0;
}
