#!/usr/bin/env python3
"""
Читает HTML файлы из web/templates/ и генерирует C++ файл
где все шаблоны встроены как строки.
Запускается автоматически через Makefile перед компиляцией.
"""

import os
import sys

TEMPLATES_DIR = "web/templates"
OUTPUT_FILE = "web/templates_generated.hpp"

def escape_cpp_string(s):
    """Экранируем строку для C++ raw string literal."""
    # Используем R"(...)" — не нужно ничего экранировать
    # Единственная проблема: если в HTML есть )..." — заменяем разделитель
    if ')HTMLEND"' in s:
        delimiter = "TMPL"
    else:
        delimiter = "HTMLEND"
    return f'R"{delimiter}({s}){delimiter}"'

def main():
    if not os.path.isdir(TEMPLATES_DIR):
        print(f"Error: directory {TEMPLATES_DIR} not found", file=sys.stderr)
        sys.exit(1)

    templates = {}
    for filename in sorted(os.listdir(TEMPLATES_DIR)):
        if filename.endswith(".html"):
            name = filename.replace(".html", "").replace("-", "_").upper()
            filepath = os.path.join(TEMPLATES_DIR, filename)
            with open(filepath, "r", encoding="utf-8") as f:
                content = f.read()
            templates[name] = content

    lines = []
    lines.append("// AUTO-GENERATED FILE — DO NOT EDIT")
    lines.append("// Generated by embed_templates.py from web/templates/")
    lines.append("#pragma once")
    lines.append("#include <string>")
    lines.append("")
    lines.append("namespace Templates {")
    lines.append("")

    for name, content in templates.items():
        lines.append(f"inline const std::string {name} = {escape_cpp_string(content)};")
        lines.append("")

    lines.append("} // namespace Templates")

    output = "\n".join(lines)
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(output)

    print(f"Generated {OUTPUT_FILE} with {len(templates)} templates: {', '.join(templates.keys())}")

if __name__ == "__main__":
    main()
