// AUTO-GENERATED FILE — DO NOT EDIT
// Generated by embed_templates from web/templates/
#pragma once
#include <string>

namespace Templates {

inline const std::string ABOUT = R"HTMLEND(
<div class="card">
    <h2>{{TITLE}}</h2>
    <p style="color:#aaa; line-height:1.7; margin-bottom:15px;">{{DESC}}</p>
    <h3>{{IMPLEMENTED}}</h3>
    <ul>
        <li>AES-128 encryption/decryption</li>
        <li>RSA-2048 key generation and encryption</li>
        <li>BigInt (GMP)</li>
        <li>Miller-Rabin primality test</li>
        <li>SHA-256</li>
        <li>HMAC-SHA256 &amp; PBKDF2</li>
    </ul>
</div>
)HTMLEND";

inline const std::string DECRYPT = R"HTMLEND(
<div class="card">
    <h2>{{TITLE}}</h2>
    <form method="POST" action="/decrypt">
        <label>{{LABEL_PASSWORD}}</label>
        <input type="password" name="password" required placeholder="{{PLACEHOLDER_PASSWORD}}">
        <label>{{LABEL_CIPHERTEXT}}</label>
        <textarea name="ciphertext" rows="3" required placeholder="{{PLACEHOLDER_CIPHERTEXT}}"></textarea>
        <label>{{LABEL_SALT}}</label>
        <textarea name="salt" rows="2" required placeholder="{{PLACEHOLDER_SALT}}"></textarea>
        <button type="submit">{{BTN}}</button>
    </form>
</div>
{{RESULT}}
)HTMLEND";

inline const std::string DOCS_EN = R"HTMLEND(
<div class="card">
    <h2>Source Code</h2>
    <p style="color:#aaa; line-height:1.7;">Project source code is available on GitHub:</p>
    <a href="https://github.com/" class="button" style="background:#333; color:#0f0; margin-top:10px;" target="_blank">GitHub &rarr;</a>
</div>
<div class="card">
    <h2>Introduction to Encryption</h2>
    <p style="color:#aaa; line-height:1.8;">Encryption converts data into unreadable form using math. Two main types:</p>
    <ul style="margin-top:10px;">
        <li><strong style="color:#eee;">Symmetric</strong> — one key for encrypt and decrypt. Fast. Example: AES.</li>
        <li><strong style="color:#eee;">Asymmetric</strong> — public key encrypts, private key decrypts. Example: RSA.</li>
    </ul>
</div>
<div class="card">
    <h2>AES-128</h2>
    <p style="color:#aaa; line-height:1.8; margin-bottom:12px;">AES (Advanced Encryption Standard) — symmetric block cipher, NIST standard since 2001. Encrypts 128-bit blocks with 128-bit key.</p>
    <h3>How it works</h3>
    <ul>
        <li>Data split into 4x4 byte blocks (128 bits)</li>
        <li>10 rounds of transformations per block</li>
        <li><strong style="color:#eee;">SubBytes</strong> — byte substitution via S-Box</li>
        <li><strong style="color:#eee;">ShiftRows</strong> — cyclic row shifts</li>
        <li><strong style="color:#eee;">MixColumns</strong> — column mixing in GF(2^8)</li>
        <li><strong style="color:#eee;">AddRoundKey</strong> — XOR with round key</li>
    </ul>
    <h3 style="margin-top:15px;">Implementation</h3>
    <ul>
        <li>Password to key via PBKDF2-HMAC-SHA256 (10000 iterations)</li>
        <li>Random salt (16 bytes) per encryption</li>
        <li>ECB mode with PKCS#7 padding</li>
    </ul>
    <p style="color:#777; font-size:12px; margin-top:10px;">Spec: FIPS 197 — <a href="https://csrc.nist.gov/pubs/fips/197/final" target="_blank">csrc.nist.gov/pubs/fips/197/final</a></p>
</div>
<div class="card">
    <h2>RSA-2048</h2>
    <p style="color:#aaa; line-height:1.8; margin-bottom:12px;">Asymmetric encryption by Rivest, Shamir, Adleman (1977). Security based on difficulty of factoring large numbers.</p>
    <h3>Key Generation</h3>
    <ul>
        <li>Two primes <strong style="color:#eee;">p</strong> and <strong style="color:#eee;">q</strong> (1024 bits each)</li>
        <li>Modulus <strong style="color:#eee;">n = p x q</strong> (2048 bits)</li>
        <li>Euler totient <strong style="color:#eee;">phi(n) = (p-1)(q-1)</strong></li>
        <li>Public exponent <strong style="color:#eee;">e = 65537</strong></li>
        <li>Private exponent <strong style="color:#eee;">d = e^(-1) mod phi(n)</strong></li>
    </ul>
    <h3 style="margin-top:15px;">Encrypt / Decrypt</h3>
    <ul>
        <li>Encrypt: <strong style="color:#eee;">c = m^e mod n</strong></li>
        <li>Decrypt: <strong style="color:#eee;">m = c^d mod n</strong></li>
        <li>Messages split into 223-byte blocks</li>
    </ul>
    <p style="color:#777; font-size:12px; margin-top:10px;">Spec: RFC 8017 — <a href="https://www.rfc-editor.org/rfc/rfc8017" target="_blank">rfc-editor.org/rfc/rfc8017</a></p>
</div>
<div class="card">
    <h2>SHA-256</h2>
    <p style="color:#aaa; line-height:1.8;">Cryptographic hash from SHA-2 family. Converts any data to 256-bit hash. Used in HMAC and PBKDF2.</p>
    <ul style="margin-top:10px;">
        <li>512-bit blocks, 64 compression rounds</li>
        <li>AND, OR, XOR, NOT and bit shifts</li>
        <li>One-way: cannot recover original data from hash</li>
    </ul>
    <p style="color:#777; font-size:12px; margin-top:10px;">Spec: FIPS 180-4 — <a href="https://csrc.nist.gov/pubs/fips/180-4/upd1/final" target="_blank">csrc.nist.gov/pubs/fips/180-4</a></p>
</div>
<div class="card">
    <h2>Libraries Used</h2>
    <ul>
        <li><strong style="color:#eee;">GMP</strong> — big number arithmetic for RSA (+, -, x, /, mod only).<br><a href="https://gmplib.org/" target="_blank" style="font-size:12px;">gmplib.org</a></li>
        <li style="margin-top:10px;"><strong style="color:#eee;">cpp-httplib</strong> — single-file C++ HTTP library.<br><a href="https://github.com/yhirose/cpp-httplib" target="_blank" style="font-size:12px;">github.com/yhirose/cpp-httplib</a></li>
    </ul>
    <p style="color:#aaa; line-height:1.8; margin-top:15px;">All crypto algorithms implemented from scratch without third-party crypto libraries.</p>
</div>
)HTMLEND";

inline const std::string DOCS_RU = R"HTMLEND(
<div class="card">
    <h2>Исходный код</h2>
    <p style="color:#aaa; line-height:1.7;">Исходный код проекта доступен на GitHub:</p>
    <a href="https://github.com/" class="button" style="background:#333; color:#0f0; margin-top:10px;" target="_blank">GitHub &rarr;</a>
</div>
<div class="card">
    <h2>Общие сведения о шифровании</h2>
    <p style="color:#aaa; line-height:1.8;">Шифрование — процесс преобразования данных в нечитаемый вид. Существует два основных вида:</p>
    <ul style="margin-top:10px;">
        <li><strong style="color:#eee;">Симметричное</strong> — один ключ для шифрования и расшифрования. Быстрое. Пример: AES.</li>
        <li><strong style="color:#eee;">Асимметричное</strong> — публичный ключ шифрует, приватный расшифровывает. Пример: RSA.</li>
    </ul>
</div>
<div class="card">
    <h2>AES-128</h2>
    <p style="color:#aaa; line-height:1.8; margin-bottom:12px;">AES (Advanced Encryption Standard) — симметричный блочный шифр, стандарт NIST с 2001 года. Шифрует блоками 128 бит с ключом 128 бит.</p>
    <h3>Как работает</h3>
    <ul>
        <li>Данные разбиваются на блоки 4x4 байта (128 бит)</li>
        <li>Каждый блок проходит 10 раундов преобразований</li>
        <li><strong style="color:#eee;">SubBytes</strong> — замена байт по таблице S-Box</li>
        <li><strong style="color:#eee;">ShiftRows</strong> — циклический сдвиг строк матрицы</li>
        <li><strong style="color:#eee;">MixColumns</strong> — перемешивание столбцов в GF(2^8)</li>
        <li><strong style="color:#eee;">AddRoundKey</strong> — XOR с раундовым ключом</li>
    </ul>
    <h3 style="margin-top:15px;">Особенности реализации</h3>
    <ul>
        <li>Пароль -> ключ через PBKDF2-HMAC-SHA256 (10000 итераций)</li>
        <li>Случайная соль (16 байт) для каждого шифрования</li>
        <li>Режим ECB с PKCS#7 padding</li>
    </ul>
    <p style="color:#777; font-size:12px; margin-top:10px;">Спецификация: FIPS 197 — <a href="https://csrc.nist.gov/pubs/fips/197/final" target="_blank">csrc.nist.gov/pubs/fips/197/final</a></p>
</div>
<div class="card">
    <h2>RSA-2048</h2>
    <p style="color:#aaa; line-height:1.8; margin-bottom:12px;">RSA — асимметричный алгоритм (Rivest, Shamir, Adleman, 1977). Безопасность основана на сложности факторизации больших чисел.</p>
    <h3>Генерация ключей</h3>
    <ul>
        <li>Два больших простых числа <strong style="color:#eee;">p</strong> и <strong style="color:#eee;">q</strong> (по 1024 бита)</li>
        <li>Модуль <strong style="color:#eee;">n = p x q</strong> (2048 бит)</li>
        <li>Функция Эйлера <strong style="color:#eee;">phi(n) = (p-1)(q-1)</strong></li>
        <li>Публичная экспонента <strong style="color:#eee;">e = 65537</strong></li>
        <li>Приватная экспонента <strong style="color:#eee;">d = e^(-1) mod phi(n)</strong></li>
    </ul>
    <h3 style="margin-top:15px;">Шифрование / расшифрование</h3>
    <ul>
        <li>Шифрование: <strong style="color:#eee;">c = m^e mod n</strong></li>
        <li>Расшифрование: <strong style="color:#eee;">m = c^d mod n</strong></li>
        <li>Длинные сообщения разбиваются на блоки по 223 байта</li>
    </ul>
    <h3 style="margin-top:15px;">Проверка простоты</h3>
    <p style="color:#aaa; line-height:1.8;">Тест Миллера-Рабина (20 раундов). Вероятность ошибки менее 2^(-40). Предварительная фильтрация первыми 170 малыми простыми.</p>
    <p style="color:#777; font-size:12px; margin-top:10px;">Спецификация: RFC 8017 — <a href="https://www.rfc-editor.org/rfc/rfc8017" target="_blank">rfc-editor.org/rfc/rfc8017</a></p>
</div>
<div class="card">
    <h2>SHA-256</h2>
    <p style="color:#aaa; line-height:1.8;">Криптографическая хеш-функция SHA-2. Преобразует данные любой длины в 256-битный хеш. Используется в HMAC и PBKDF2.</p>
    <ul style="margin-top:10px;">
        <li>Блоки по 512 бит, 64 раунда сжатия</li>
        <li>Операции AND, OR, XOR, NOT и битовые сдвиги</li>
        <li>Необратима: нельзя восстановить исходные данные из хеша</li>
    </ul>
    <p style="color:#777; font-size:12px; margin-top:10px;">Спецификация: FIPS 180-4 — <a href="https://csrc.nist.gov/pubs/fips/180-4/upd1/final" target="_blank">csrc.nist.gov/pubs/fips/180-4</a></p>
</div>
<div class="card">
    <h2>Используемые библиотеки</h2>
    <ul>
        <li><strong style="color:#eee;">GMP</strong> — арифметика больших чисел для RSA (только +, -, x, /, mod).<br><a href="https://gmplib.org/" target="_blank" style="font-size:12px;">gmplib.org</a></li>
        <li style="margin-top:10px;"><strong style="color:#eee;">cpp-httplib</strong> — однофайловая C++ HTTP библиотека.<br><a href="https://github.com/yhirose/cpp-httplib" target="_blank" style="font-size:12px;">github.com/yhirose/cpp-httplib</a></li>
    </ul>
    <p style="color:#aaa; line-height:1.8; margin-top:15px;">Все криптографические алгоритмы реализованы самостоятельно без сторонних криптобиблиотек.</p>
</div>
)HTMLEND";

inline const std::string ENCRYPT = R"HTMLEND(
<div class="card">
    <h2>{{TITLE}}</h2>
    <form method="POST" action="/encrypt">
        <label>{{LABEL_PASSWORD}}</label>
        <input type="password" name="password" required placeholder="{{PLACEHOLDER_PASSWORD}}">
        <label>{{LABEL_PLAINTEXT}}</label>
        <textarea name="plaintext" rows="6" required placeholder="{{PLACEHOLDER_PLAINTEXT}}"></textarea>
        <button type="submit">{{BTN}}</button>
    </form>
</div>
{{RESULT}}
)HTMLEND";

inline const std::string HOME = R"HTMLEND(
<div class="card">
    <h2>{{HOME_TITLE}}</h2>
    <p style="color:#aaa; line-height:1.7;">{{HOME_DESC}}</p>
    <div class="button-group">
        <a href="/encrypt" class="button">{{BTN_ENCRYPT}}</a>
        <a href="/rsa/generate" class="button" style="background:#333; color:#0f0;">{{BTN_RSA}}</a>
    </div>
</div>
<div class="card">
    <h3>{{ALGORITHMS}}</h3>
    <div class="stats-grid">
        <div class="stat-card"><div class="stat-value">AES-128</div><div class="stat-label">{{SYMMETRIC}}</div></div>
        <div class="stat-card"><div class="stat-value">RSA-2048</div><div class="stat-label">{{ASYMMETRIC}}</div></div>
        <div class="stat-card"><div class="stat-value">SHA-256</div><div class="stat-label">{{HASH}}</div></div>
        <div class="stat-card"><div class="stat-value">PBKDF2</div><div class="stat-label">{{KEY_DERIV}}</div></div>
    </div>
</div>
)HTMLEND";

inline const std::string RSA_DECRYPT = R"HTMLEND(
<div class="card">
    <h2>{{TITLE}}</h2>
    <form method="POST" action="/rsa/decrypt">
        <label>{{LABEL_N}}</label>
        <textarea name="privkey_n" rows="6" required placeholder="{{PLACEHOLDER_N}}"></textarea>
        <label>{{LABEL_D}}</label>
        <textarea name="privkey_d" rows="6" required placeholder="{{PLACEHOLDER_D}}"></textarea>
        <label>{{LABEL_CIPHER}}</label>
        <textarea name="ciphertext" rows="4" required placeholder="{{PLACEHOLDER_CIPHER}}"></textarea>
        <button type="submit">{{BTN}}</button>
    </form>
</div>
{{RESULT}}
)HTMLEND";

inline const std::string RSA_ENCRYPT = R"HTMLEND(
<div class="card">
    <h2>{{TITLE}}</h2>
    <form method="POST" action="/rsa/encrypt">
        <label>{{LABEL_N}}</label>
        <textarea name="pubkey_n" rows="6" required placeholder="{{PLACEHOLDER_N}}"></textarea>
        <label>{{LABEL_E}}</label>
        <input type="text" name="pubkey_e" required placeholder="{{PLACEHOLDER_E}}">
        <label>{{LABEL_PLAINTEXT}}</label>
        <textarea name="plaintext" rows="4" required placeholder="{{PLACEHOLDER_PLAINTEXT}}"></textarea>
        <button type="submit">{{BTN}}</button>
    </form>
</div>
{{RESULT}}
)HTMLEND";

inline const std::string RSA_GENERATE = R"HTMLEND(
<div class="card">
    <h2>{{TITLE}}</h2>
    <p style="color:#aaa; margin-bottom:15px;">{{WARNING}}</p>
    <form method="POST" action="/rsa/generate">
        <button type="submit">{{BTN}}</button>
    </form>
</div>
{{RESULT}}
)HTMLEND";

inline const std::string TEST = R"HTMLEND(
<div class="card">
    <h2>{{TITLE}}</h2>
    <p style="color:#aaa; margin-bottom:15px;">{{DESC}}</p>
    <form method="POST" action="/test">
        <button type="submit">{{BTN}}</button>
    </form>
</div>
{{RESULT}}
)HTMLEND";

} // namespace Templates
